language: java
jdk: oraclejdk9

#env:
#- COVERAGE=0.35
#- COVERAGE=0.5

install:
- ./gradlew clean jar

stages:
- test

jobs:
  include:
    - stage: test
	    name:"coverage = 0.5"
		install: skip
	    #script:
		#- COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
#	    env:
#	    - COVERAGE=0.5

#after_success:
#- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

#deploy:
#  provider: script
#  script: echo 'WIP'
#  on:
#    all_branches: true