language: java
jdk: oraclejdk9

env:
- COVERAGE=0.35
- COVERAGE=0.5

install:
- ./gradlew clean jar

stages:
- test
- deploy

jobs:
  include:
    - stage: test
	  script: ./gradlew -p
	- stage: test
	  script: ./gradlew -p
	   # name:"coverage = 0.5"
		#install: skip
#		env:
#	    - COVERAGE=0.5

	  # ./monolithic/ui check


#after_success:
#- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

#deploy:
#  provider: script
#  script: echo 'WIP'
#  on:
#    all_branches: true