language: java
jdk: oraclejdk9

env:
- COVERAGE=0.35
- COVERAGE=0.5

install:
- ./gradlew clean jar

jobs:
  include:
    - stage: test
	  env: COVERAGE=0.5
	  install: 
	  - ./gradlew clean jar
	  script: 
	  - ./gradlew test