language: java
jdk: oraclejdk9

env:
- COVERAGE=0.35
- COVERAGE=0.5

stages:
- test
- check

jobs:
  include:
    - stage: check
	  install:
      - ./gradlew clean jar
	  script: 
	  - ./gradlew -p ./monolithic/ui check
	  env: 
	  - COVERAGE=0.5

after_success:
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true