language: java
jdk: oraclejdk9

env:
- COVERAGE=0.35
- COVERAGE=0.5

stages:
- test
- deploy

jobs:
  include:
    - stage: test
	  name:"test"
	  install: ./gradlew clean jar
	  script:
	  - ./gradlew -p ./monolithic/ui check
	  env:
	  - COVERAGE=0.35