language: java
jdk: 
- oraclejdk9
- oraclejdk14


env:
- COVERAGE=0.5 BUILD_TARGET=./monolithic/ui
- COVERAGE=0.5 BUILD_TARGET=./monolithic/service/cart
- COVERAGE=0.5 BUILD_TARGET=./monolithic/service/user

- COVERAGE=0.24 BUILD_TARGET=./monolithic/repository/order
- COVERAGE=0.5 BUILD_TARGET=./monolithic/repository/cart
- COVERAGE=0.5 BUILD_TARGET=./monolithic/repository/product
- COVERAGE=0.24 BUILD_TARGET=./monolithic/repository/user

before_install:
- travis encrypt DOCKER_LOGIN=paulschellenberger --add env.global
- travis encrypt DOCKER_PASSWORD=dke83Uvl@R --add env.global

install:
- ./gradlew clean jar

script:
- ./gradlew -p $BUILD_TARGET check

after_success:
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
- bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"

