language: java
jdk: oraclejdk9

env:
- COVERAGE=0.35
- COVERAGE=0.5

install:
- ./gradlew clean jar

stages:
- test
- deploy

jobs:
  include:
    - stage: test
		name:"Test1"
#	  install: skip
		script: 
		- ./gradlew test
	- stage: test
		name:"Test2"
#	  install: skip
		script: 
		- ./gradlew test
#	  script: COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
#	- stage: test
#	  script: COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
	   # name:"coverage = 0.5"
		#install: skip
#		env:
#	    - COVERAGE=0.5

	  # ./monolithic/ui check


#after_success:
#- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

#deploy:
#  provider: script
#  script: echo 'WIP'
#  on:
#    all_branches: true